/**
 * Product enrichment map — generated by scripts/buildEnrichment.mjs.
 *
 * Keys are showcase item ids (`item.f`); values are product keys whose names appear
 * inside that infographic but nowhere in its text metadata. showcaseData.js expands
 * each key into its phrase(s) and merges them into the item's `extraKeywords`, so
 * ecosystem product nodes and free-text search both resolve against them.
 *
 * Totals (of 235): xenia 4 · domi 4 · kombos 64 · cielo 22 · mints 6;
 * 4 plates carry all five (IMG_0557.jpg, IMG_0558.jpg, IMG_0559.jpg, IMG_0560.jpg) and were verified against the artwork.
 */

export const PRODUCTS = {
  xenia: { key: 'xenia', name: "Caleido Xenia", token: 'xenia', phrases: ["caleido xenia"] },
  domi: { key: 'domi', name: "Caleido Domi", token: 'domi', phrases: ["caleido domi"] },
  kombos: { key: 'kombos', name: "Caleido Kombos", token: 'kombos', phrases: ["caleido kombos"] },
  cielo: { key: 'cielo', name: "Cielo Epic", token: 'cielo', phrases: ["cielo epic"] },
  mints: { key: 'mints', name: "Caleido Mints", token: 'mints', phrases: ["caleido mints","cm"] },
}

export const PRODUCT_ENRICHMENT = {
  "1BClb25V8HI0_Uxpwg-8u.jpg": [
    "kombos"
  ],
  "23lJ2ln5Hx2JnzmOPric-.jpg": [
    "cielo"
  ],
  "2TYCw_5fzraTW2YXuxskG.jpg": [
    "cielo",
    "kombos"
  ],
  "ADYt3Y1_f5nZysHBxpO9r.jpg": [
    "kombos"
  ],
  "EHs0TVB7SmnltdBXzSNGf.jpg": [
    "cielo"
  ],
  "EKSaQ7o_nYaYIIdEQ8nwI.jpg": [
    "kombos"
  ],
  "EoPhGEttZjOKV_RnA2jf6.jpg": [
    "kombos"
  ],
  "IMG_0557.jpg": [
    "cielo",
    "domi",
    "kombos",
    "mints",
    "xenia"
  ],
  "IMG_0558.jpg": [
    "cielo",
    "domi",
    "kombos",
    "mints",
    "xenia"
  ],
  "IMG_0559.jpg": [
    "cielo",
    "domi",
    "kombos",
    "mints",
    "xenia"
  ],
  "IMG_0560.jpg": [
    "cielo",
    "domi",
    "kombos",
    "mints",
    "xenia"
  ],
  "IMG_0600.jpg": [
    "cielo",
    "kombos"
  ],
  "IMG_0603.jpg": [
    "kombos"
  ],
  "IMG_0604.jpg": [
    "kombos"
  ],
  "IMG_0608.jpg": [
    "kombos"
  ],
  "IMG_0609.jpg": [
    "cielo",
    "kombos"
  ],
  "IMG_0611.jpg": [
    "kombos"
  ],
  "IMG_0612.jpg": [
    "kombos"
  ],
  "IMG_0613.jpg": [
    "kombos"
  ],
  "IMG_0615.jpg": [
    "cielo",
    "kombos"
  ],
  "IMG_0616.jpg": [
    "cielo",
    "kombos"
  ],
  "IMG_0617.jpg": [
    "cielo",
    "kombos"
  ],
  "IMG_0618.jpg": [
    "cielo"
  ],
  "IMG_0621.jpg": [
    "cielo",
    "kombos"
  ],
  "IMG_0623.jpg": [
    "cielo"
  ],
  "IMG_0624.jpg": [
    "kombos"
  ],
  "IMG_0628.jpg": [
    "kombos"
  ],
  "IMG_0630.jpg": [
    "cielo",
    "kombos"
  ],
  "IMG_0634.jpg": [
    "kombos"
  ],
  "IMG_0637.jpg": [
    "kombos"
  ],
  "IMG_0638.jpg": [
    "cielo"
  ],
  "IMG_0642.jpg": [
    "kombos"
  ],
  "IMG_0643.jpg": [
    "kombos"
  ],
  "IMG_0644.jpg": [
    "kombos"
  ],
  "IMG_0645.jpg": [
    "kombos"
  ],
  "IMG_0647.jpg": [
    "mints"
  ],
  "IMG_0649.jpg": [
    "cielo"
  ],
  "IMG_0650.jpg": [
    "kombos"
  ],
  "IMG_0657.jpg": [
    "kombos"
  ],
  "IMG_0660.jpg": [
    "cielo"
  ],
  "IMG_0661.jpg": [
    "kombos"
  ],
  "IMG_0665.jpg": [
    "cielo",
    "kombos",
    "mints"
  ],
  "IMG_0667.jpg": [
    "kombos"
  ],
  "IMG_0669.jpg": [
    "kombos"
  ],
  "IMG_0676.jpg": [
    "kombos"
  ],
  "IMG_0678.jpg": [
    "kombos"
  ],
  "IMG_0679.jpg": [
    "kombos"
  ],
  "IMG_0680.jpg": [
    "kombos"
  ],
  "IMG_0686.jpg": [
    "kombos"
  ],
  "IMG_0687.jpg": [
    "kombos"
  ],
  "IMG_0689.jpg": [
    "kombos"
  ],
  "IMG_0691.jpg": [
    "kombos"
  ],
  "IMG_0715.jpg": [
    "kombos"
  ],
  "IMG_0747.jpg": [
    "kombos"
  ],
  "IMG_0749.jpg": [
    "kombos"
  ],
  "IMG_0753.jpg": [
    "kombos"
  ],
  "IMG_0761.jpg": [
    "kombos"
  ],
  "IMG_0773.jpg": [
    "kombos"
  ],
  "IMG_0774.jpg": [
    "cielo"
  ],
  "IMG_0775.jpg": [
    "kombos"
  ],
  "IMG_0776.jpg": [
    "kombos"
  ],
  "IMG_0779.jpg": [
    "kombos"
  ],
  "IMG_0780.jpg": [
    "kombos"
  ],
  "IMG_0781.jpg": [
    "kombos"
  ],
  "IMG_0783.jpg": [
    "kombos"
  ],
  "PDKjfGBX3Za8CeLuNhEbb.jpg": [
    "kombos"
  ],
  "UqyOv8c0jYNESkFuxtwdq.jpg": [
    "kombos"
  ],
  "WPnnIUsJKNzgVwHREcpS8.jpg": [
    "cielo",
    "kombos"
  ],
  "dwwp--kFEn6VoT4uggfP_.jpg": [
    "kombos"
  ],
  "fJkG12Tu8B0wp9LUj_I2H.jpg": [
    "kombos"
  ],
  "gPNAogBxS6jm-mJ46okFq.jpg": [
    "kombos"
  ],
  "qDh8go04o7CY7oKpoDo2f.jpg": [
    "kombos"
  ],
  "tbJATFUKvtdra7QY_FeXb.jpg": [
    "kombos"
  ]
}

/** Phrases to merge into an item's extraKeywords, given its `f` id. */
export function enrichmentFor(f) {
  const keys = PRODUCT_ENRICHMENT[f]
  if (!keys) return []
  return keys.flatMap((k) => PRODUCTS[k]?.phrases ?? [])
}

/** Product keys carried by an item id, e.g. ['kombos', 'cielo']. */
export function productKeysFor(f) {
  return PRODUCT_ENRICHMENT[f] ?? []
}
